"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
import toml

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# --- Загрузка настроек из TOML файла ---
CONFIG_FILE = os.path.join(BASE_DIR, 'config.toml')

if not os.path.exists(CONFIG_FILE):
    raise FileNotFoundError(f"Configuration file not found: {CONFIG_FILE}")

try:
    with open(CONFIG_FILE, 'r') as f:
        config = toml.load(f)
except toml.TomlDecodeError as e:
    raise ValueError(f"Error decoding TOML file: {e}")

# Функции для безопасного получения значений
def get_config_setting(section, key, default=None):
    return config.get(section, {}).get(key, default)

def get_config_setting_required(section, key):
    value = get_config_setting(section, key)
    if value is None:
        raise ValueError(f"Missing required setting in config.toml: [{section}].{key}")
    return value
# --- Конец блока загрузки настроек из TOML файла ---


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_config_setting_required('django', 'SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_config_setting('django', 'DEBUG', default=False)

ALLOWED_HOSTS = get_config_setting('django', 'ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'users',
    'files',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


DATABASES = {
    "default": {
        "ENGINE": get_config_setting_required('database', 'ENGINE'),
        "NAME": get_config_setting_required('database', 'NAME'),
        "USER": get_config_setting_required('database', 'USER'),
        "PASSWORD": get_config_setting_required('database', 'PASSWORD'),
        "HOST": get_config_setting_required('database', 'HOST'),
        "PORT": get_config_setting_required('database', 'PORT'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': get_config_setting('rest_framework', 'DEFAULT_PAGINATION_CLASS',
                                                default='rest_framework.pagination.PageNumberPagination'),
    'PAGE_SIZE': get_config_setting('rest_framework', 'PAGE_SIZE', default=100),
}

CORS_ALLOWED_ORIGINS = get_config_setting('cors', 'ALLOWED_ORIGINS', default=[])
CORS_ALLOW_CREDENTIALS = get_config_setting('cors', 'ALLOW_CREDENTIALS', default=False)
CORS_ALLOW_HEADERS = get_config_setting('cors', 'ALLOW_HEADERS', default=[])
CORS_EXPOSE_HEADERS = get_config_setting('cors', 'EXPOSE_HEADERS', default=[])

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = "credentialless"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_URL = get_config_setting('django', 'SITE_URL', default='http://127.0.0.1:8000')

if not os.path.exists(os.path.join(BASE_DIR, 'logs')):
    os.makedirs(os.path.join(BASE_DIR, 'logs'))


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/debug.log'),
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', get_config_setting('logging.loggers.users', 'LEVEL', 'INFO')),
            'propagate': True,
        },
        'files': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', get_config_setting('logging.loggers.files', 'LEVEL', 'INFO')),
            'propagate': True,
        },
    },
}


TESTING_MEDIA_ROOT = os.path.join(BASE_DIR, 'test_media')

if 'test' in sys.argv:
    MEDIA_ROOT = TESTING_MEDIA_ROOT