# Generated by Django 5.2.7 on 2025-11-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_full_name_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='storage_path',
            field=models.CharField(blank=True, default='user_files/<username>', max_length=255),
        ),
    ]
