# Generated by Django 5.2.7 on 2025-10-28 09:44

import django.db.models.deletion
import files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=files.models.generate_unique_filename)),
                ('comment', models.TextField(blank=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_download_date', models.DateTimeField(blank=True, null=True)),
                ('special_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
